a = {'city': {'geoname_id': 5037649,
              'names': {'de': 'Minneapolis', 'en': 'Minneapolis', 'es': 'Mineápolis', 'fr': 'Minneapolis',
                        'ja': 'ミネアポリス',
                        'pt-BR': 'Minneapolis', 'ru': 'Миннеаполис', 'zh-CN': '明尼阿波利斯'}},
     'continent': {'code': 'NA', 'geoname_id': 6255149,
                   'names': {'de': 'Nordamerika', 'en': 'North America', 'es': 'Norteamérica', 'fr': 'Amérique du Nord',
                             'ja': '北アメリカ', 'pt-BR': 'América do Norte', 'ru': 'Северная Америка', 'zh-CN': '北美洲'}},
     'country': {'geoname_id': 6252001, 'iso_code': 'US',
                 'names': {'de': 'USA', 'en': 'United States', 'es': 'EE. UU.', 'fr': 'É.-U.', 'ja': 'アメリカ',
                           'pt-BR': 'EUA',
                           'ru': 'США', 'zh-CN': '美国'}},
     'location': {'accuracy_radius': 20, 'latitude': 45.0546, 'longitude': -93.2566, 'metro_code': 613,
                  'time_zone': 'America/Chicago'}, 'postal': {'code': '55421'},
     'registered_country': {'geoname_id': 6252001, 'iso_code': 'US',
                            'names': {'de': 'USA', 'en': 'United States', 'es': 'EE. UU.', 'fr': 'É.-U.', 'ja': 'アメリカ',
                                      'pt-BR': 'EUA', 'ru': 'США', 'zh-CN': '美国'}}, 'subdivisions': [
        {'geoname_id': 5037779, 'iso_code': 'MN',
         'names': {'en': 'Minnesota', 'es': 'Minnesota', 'fr': 'Minnesota', 'ja': 'ミネソタ州', 'pt-BR': 'Minesota',
                   'ru': 'Миннесота', 'zh-CN': '明尼苏达州'}}],
     'traits': {'ip_address': '128.101.101.101', 'prefix_len': 21}}
